name=input("Enter name:")
print(name)
Father name=input("Ente fatgher name")
print (Father name)
age=input("Enter age:")
print(age)
univercity=input("Enter your univercity name")
print(univercity)
hobby=input("your favorite hobby")
print(hobby)
book=input("your favorite book")
print(book)
meal=input("your favorite meal")
print(meal)
adress=input("you location adress")
print(adress)
email adress=input("enter email")
print(email)
instagram=input("enter your name in instagram")
print(instagram)
phone=input("enter phon number")
print(phone)